import "./accounttests/RegistrationTest.cy"
import "./accounttests/LoginTests.cy"
import "./portfolioTest/WebLinkTest.cy"
import "./userlist/usersPerPage.cy"
import "./evidenceTests/FilteringByCategoriesAndSkills.cy"
import "./calendarTests/RestrictDatesTests.cy"
import "./calendarTests/RestrictDatesTests.cy"